export const ACCOUNT_COPY = Object.freeze({
  zh: Object.freeze({
    title: "设置",
    sub: "改用户名、密码或邮箱。换邮箱要用验证码。",
    username: "用户名",
    saveName: "保存用户名",
    password: "密码",
    current: "当前密码",
    next: "新密码",
    next2: "再输一次新密码",
    savePass: "保存密码",
    email: "邮箱",
    newEmail: "新邮箱",
    sendCode: "发送验证码",
    code: "验证码",
    confirmEmail: "确认换邮箱",
    ok: "已保存",
    sent: "验证码已发到新邮箱",
  }),
  en: Object.freeze({
    title: "Settings",
    sub: "Change your name, password, or email. Email changes use a code.",
    username: "Username",
    saveName: "Save name",
    password: "Password",
    current: "Current password",
    next: "New password",
    next2: "New password again",
    savePass: "Save password",
    email: "Email",
    newEmail: "New email",
    sendCode: "Send code",
    code: "Code",
    confirmEmail: "Confirm email",
    ok: "Saved",
    sent: "Code sent to the new address",
  }),
  ja: Object.freeze({
    title: "設定",
    sub: "名前・パスワード・メールを変更。メール変更は確認コードです。",
    username: "ユーザー名",
    saveName: "名前を保存",
    password: "パスワード",
    current: "現在のパスワード",
    next: "新しいパスワード",
    next2: "もう一度",
    savePass: "パスワードを保存",
    email: "メール",
    newEmail: "新しいメール",
    sendCode: "コード送信",
    code: "確認コード",
    confirmEmail: "メールを確定",
    ok: "保存しました",
    sent: "新しい宛先にコードを送りました",
  }),
});

export function accountCopy(lang) {
  return ACCOUNT_COPY[lang] || ACCOUNT_COPY.en;
}
