plugins { id "com.android.application" }
android {
  namespace "com.p1024201.ft"
  compileSdk 33
  buildToolsVersion "33.0.2"
  defaultConfig {
    applicationId "com.p1024201.ft"
    minSdk 21
    targetSdk 28
    versionCode 7
    versionName "1.6"
  }
  buildTypes { release { minifyEnabled false } }
}
dependencies { implementation "androidx.appcompat:appcompat:1.6.1" }
