export const ROOMS_COPY = Object.freeze({
  zh: Object.freeze({
    title: "开房",
    sub: "登录后才能进。游戏房先只开对圈；对局同步下一期。",
    tabGame: "游戏开房",
    tabChat: "聊天开房",
    create: "开房",
    name: "房间名",
    game: "游戏",
    gameDua: "对圈",
    gameBlurb: "目前能联机的只有对圈，最多三人。",
    pin: "口令（可空）",
    unlimited: "不限人数",
    pinPh: "4 位数字",
    namePh: "给房间起个名",
    list: "房间列表",
    empty: "还没有房间。",
    join: "进入",
    needPin: "输入口令",
    leave: "离开",
    close: "关闭房间",
    closeAsk: "关闭后房间和聊天记录都会删掉。确定关吗？",
    cancel: "取消",
    ok: "确定",
    say: "发送",
    chatPh: "说一句…",
    seatsNow: "在座",
    code: "房号",
    host: "房主",
    locked: "有口令",
    duaSoon: "对圈联机同步还没接上。先在房间里等人，或去单机练习。",
    practice: "练习",
    ready: "准备",
    unready: "取消准备",
    startMatch: "开始",
    enterDua: "进入对圈",
    login: "先登录",
    errPin: "口令不对",
    errFull: "人满了",
    errClosed: "房间已关",
  }),
  en: Object.freeze({
    title: "Rooms",
    sub: "Signed-in users only. Game rooms are Dua for now. Live match sync comes next.",
    tabGame: "Game rooms",
    tabChat: "Chat rooms",
    create: "Get a room",
    name: "Room name",
    game: "Game",
    gameDua: "Dua",
    gameBlurb: "Dua is the only online game so far. Up to three people.",
    pin: "PIN (optional)",
    unlimited: "No seat limit",
    pinPh: "4 digits",
    namePh: "Name the room",
    list: "Open rooms",
    empty: "No rooms yet.",
    join: "Join",
    needPin: "Enter PIN",
    leave: "Leave",
    close: "Close room",
    closeAsk: "Closing deletes the room and its chat. Close it?",
    cancel: "Cancel",
    ok: "OK",
    say: "Send",
    chatPh: "Say something…",
    seatsNow: "Inside",
    code: "Code",
    host: "Host",
    locked: "PIN",
    duaSoon: "Dua match sync is not wired yet. Wait here, or practice solo.",
    practice: "Practice",
    ready: "Ready",
    unready: "Not ready",
    startMatch: "Start",
    enterDua: "Enter Dua",
    login: "Sign in first",
    errPin: "Wrong PIN",
    errFull: "Room is full",
    errClosed: "Room closed",
  }),
  ja: Object.freeze({
    title: "ルーム",
    sub: "ログイン必須。ゲーム部屋は今は対圈のみ。対戦同期は次の段階。",
    tabGame: "ゲーム部屋",
    tabChat: "チャット部屋",
    create: "休憩する",
    name: "部屋名",
    game: "ゲーム",
    gameDua: "ガツン",
    gameBlurb: "今オンラインにできるのは対圈だけ。最大3人。",
    pin: "暗証（任意）",
    unlimited: "人数制限なし",
    pinPh: "4桁",
    namePh: "部屋の名前",
    list: "部屋一覧",
    empty: "まだ部屋がありません。",
    join: "入室",
    needPin: "暗証を入力",
    leave: "退出",
    close: "部屋を閉じる",
    closeAsk: "閉じると部屋とチャット記録が消えます。閉じますか？",
    cancel: "キャンセル",
    ok: "OK",
    say: "送信",
    chatPh: "ひとこと…",
    seatsNow: "在室",
    code: "部屋番号",
    host: "ホスト",
    locked: "暗証あり",
    duaSoon: "対圈の同期はまだです。ここで待つか、ソロで練習してください。",
    practice: "練習",
    ready: "準備",
    unready: "準備を戻す",
    startMatch: "開始",
    enterDua: "ガツンへ",
    login: "先にログイン",
    errPin: "暗証が違います",
    errFull: "満室です",
    errClosed: "部屋は閉じました",
  }),
});

export function roomsCopy(lang) {
  return ROOMS_COPY[lang] || ROOMS_COPY.en;
}
