export const ROOMS_COPY = Object.freeze({
  zh: Object.freeze({
    title: "开房",
    tabGame: "游戏开房",
    tabChat: "聊天开房",
    create: "开房",
    name: "房间名",
    game: "游戏",
    gameDua: "对圈",
    gameBlurb: "目前能联机的只有对圈，最多三人。",
    pin: "口令（可空）",
    unlimited: "不限人数",
    pinPh: "4 位数字",
    namePh: "给房间起个名",
    list: "房间列表",
    empty: "还没有房间。",
    join: "进入",
    needPin: "输入口令",
    leave: "离开",
    close: "关闭房间",
    closeAsk: "关闭后房间和聊天记录都会删掉。确定关吗？",
    cancel: "取消",
    ok: "确定",
    say: "发送",
    chatPh: "说一句…",
    seatsNow: "在座",
    code: "房号",
    host: "房主",
    locked: "有口令",
    practice: "练习",
    ready: "准备",
    unready: "取消准备",
    enterDua: "进入对战",
    call: "呼叫",
    called: "已呼叫",
    callNote: "房间正在呼叫练习中的人。",
    login: "先登录",
    errPin: "口令不对",
    errFull: "人满了",
    errClosed: "房间已关",
  }),
  en: Object.freeze({
    title: "Rooms",
    tabGame: "Game rooms",
    tabChat: "Chat rooms",
    create: "Get a room",
    name: "Room name",
    game: "Game",
    gameDua: "Dua",
    gameBlurb: "Dua is the only online game so far. Up to three people.",
    pin: "PIN (optional)",
    unlimited: "No seat limit",
    pinPh: "4 digits",
    namePh: "Name the room",
    list: "Open rooms",
    empty: "No rooms yet.",
    join: "Join",
    needPin: "Enter PIN",
    leave: "Leave",
    close: "Close room",
    closeAsk: "Closing deletes the room and its chat. Close it?",
    cancel: "Cancel",
    ok: "OK",
    say: "Send",
    chatPh: "Say something…",
    seatsNow: "Inside",
    code: "Code",
    host: "Host",
    locked: "PIN",
    practice: "Practice",
    ready: "Ready",
    unready: "Unready",
    enterDua: "Online Battle",
    call: "Call",
    called: "Called",
    callNote: "The room is calling people in practice.",
    login: "Sign in first",
    errPin: "Wrong PIN",
    errFull: "Room is full",
    errClosed: "Room closed",
  }),
  ja: Object.freeze({
    title: "ルーム",
    tabGame: "ゲーム部屋",
    tabChat: "チャット部屋",
    create: "休憩する",
    name: "部屋名",
    game: "ゲーム",
    gameDua: "ガツン",
    gameBlurb: "今オンラインにできるのは対圈だけ。最大3人。",
    pin: "暗証（任意）",
    unlimited: "人数制限なし",
    pinPh: "4桁",
    namePh: "部屋の名前",
    list: "部屋一覧",
    empty: "まだ部屋がありません。",
    join: "入室",
    needPin: "暗証を入力",
    leave: "退出",
    close: "部屋を閉じる",
    closeAsk: "閉じると部屋とチャット記録が消えます。閉じますか？",
    cancel: "キャンセル",
    ok: "OK",
    say: "送信",
    chatPh: "ひとこと…",
    seatsNow: "在室",
    code: "部屋番号",
    host: "ホスト",
    locked: "暗証あり",
    practice: "練習",
    ready: "準備",
    unready: "準備解除",
    enterDua: "オンライン対戦",
    call: "呼出",
    called: "呼出済み",
    callNote: "部屋が練習中の人を呼んでいます。",
    login: "先にログイン",
    errPin: "暗証が違います",
    errFull: "満室です",
    errClosed: "部屋は閉じました",
  }),
});

export function roomsCopy(lang) {
  return ROOMS_COPY[lang] || ROOMS_COPY.en;
}
